apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # The raw URL to your K3s manifest gist
  - https://gist.githubusercontent.com/21mcme04/68c7edc0b0c5653ecd2e138683f3d568/raw/37568afee75c263d8dc7db12fd2aab80fd8598b5/k3s-fogdeft-soil_moisture-manifest.yaml
  